In [1]:
import pandas as pd

In [2]:
ratings = pd.read_csv('u.data', sep='\t', names=['user_id', 'item_id', 'rating', 'timestamp'])

In [3]:
ratings

       user_id  item_id  rating  timestamp
0          196      242       3  881250949
1          186      302       3  891717742
2           22      377       1  878887116
3          244       51       2  880606923
4          166      346       1  886397596
...        ...      ...     ...        ...
99995      880      476       3  880175444
99996      716      204       5  879795543
99997      276     1090       1  874795795
99998       13      225       2  882399156
99999       12      203       3  879959583

[100000 rows x 4 columns]

In [4]:
movies = pd.read_csv('u.item', sep='|', encoding='latin-1', header=None, usecols=[0, 1])
movies.columns = ['item_id', 'title']

In [5]:
movies

      item_id                                      title
0           1                           Toy Story (1995)
1           2                           GoldenEye (1995)
2           3                          Four Rooms (1995)
3           4                          Get Shorty (1995)
4           5                             Copycat (1995)
...       ...                                        ...
1677     1678                          Mat' i syn (1997)
1678     1679                           B. Monkey (1998)
1679     1680                       Sliding Doors (1998)
1680     1681                        You So Crazy (1994)
1681     1682  Scream of Stone (Schrei aus Stein) (1991)

[1682 rows x 2 columns]

In [6]:
df = pd.merge(ratings, movies, on='item_id')

In [7]:
df

       user_id  item_id  rating  timestamp                         title
0          196      242       3  881250949                  Kolya (1996)
1          186      302       3  891717742      L.A. Confidential (1997)
2           22      377       1  878887116           Heavyweights (1994)
3          244       51       2  880606923    Legends of the Fall (1994)
4          166      346       1  886397596           Jackie Brown (1997)
...        ...      ...     ...        ...                           ...
99995      880      476       3  880175444  First Wives Club, The (1996)
99996      716      204       5  879795543     Back to the Future (1985)
99997      276     1090       1  874795795                 Sliver (1993)
99998       13      225       2  882399156         101 Dalmatians (1996)
99999       12      203       3  879959583             Unforgiven (1992)

[100000 rows x 5 columns]

In [9]:
df.isnull().sum().sum()

0